### ISSUE TITLE
%20 being added into searches

### ISSUE THREAD

**Issue by skobylite** [chrismessina/alfred-twitter-toolkit#10]
I love your workflow! I've noticed that spaces are now being replaced with %20 in the workflow recently, is there a fix I can do at my side? Thanks!

**Comment by chrismessina** [comment]
> I love your workflow! I've noticed that spaces are now being replaced with %20 in the workflow recently, is there a fix I can do at my side? Thanks!

I noticed this too! Are you on Alfred 5? 

Possibly [related discussion](https://www.alfredforum.com/topic/18573-500-ea10-double-encoding-of-url-encoded-characters-in-custom-web-search-url/) in the forum...

**Comment by chrismessina** [comment]
@skobylite this may be fixed in Alfred 5.0 EA11 ([released today](https://www.alfredforum.com/topic/18573-500-ea10-double-encoding-of-url-encoded-characters-in-custom-web-search-url/?do=findComment&comment=96744)).

Alfred 5.0 EA11

- Fix Early Access regression in URL query argument handling throughout Alfred
- Open URL workflow object
	- Improve flexibility of URL placeholder handling by offering two new options to Encode {query} and Encode {var:}
	- These are checked by default, and are best left checked under normal use of this object
	- When unchecked, options are passed to the URL processor unchanged, giving developer control over encoding
- Overhaul Accessibility for the Open URL object, with correct tab focus ordering, and better VoiceOver descriptions

**Comment by chrismessina** [comment]
Pretty sure this is fixed in [the official Alfred 5 release](https://www.alfredapp.com/blog/announcements/alfred-5-is-here/), so closing this one.
